const text = [
    `Na takich projektach i rozmowach zeszedł uszczęśliwionym dzieciom obiad. Stosunkowo najmniej zapału okazywała do zamierzonej podróży pani Olivier, której nie chciało się ruszać z wygodnej willi w Port-Saidzie i którą przestraszała myśl zamieszkania przez kilka tygodni w namiocie, a zwłaszcza zamiar wycieczek na wielbłądach. Nel, która nad wszystko w świecie lubiła jeździć na wielbłądzie, otrzymała obietnicę od ojca, że dostanie osobnego, garbatego wierzchowca, na którym wraz z panią Olivier albo z Dinah, a czasem i ze Stasiem, będzie brała udział we wspólnych wycieczkach w bliższe okolice pustyni i do Karoun.`,
    `Miało to i tę korzyść, że uczył się zarazem ich języków. Kanał Sueski nie dość było Praca przekopać, trzeba go jeszcze i utrzymać, gdyż inaczej piaski z pustyń, leżących po obu jego brzegach, zasypałyby go w ciągu roku. Wielkie dzieło Lessepsa wymaga ciągłej pracy i czujności. Toteż do dziś dnia nad pogłębieniem jego łożyska pracują pod dozorem biegłych inżynierów potężne maszyny i tysiące robotników. Przy przekopywaniu kanału pracowało ich dwadzieścia pięć tysięcy. Dziś, wobec dokonanego dzieła i ulepszonych nowych maszyn, potrzeba ich znacznie mniej, jednakże liczba ich jest dotychczas dosyć znaczna.`,
    `Miał jednak brzydki zwyczaj mówić z lekceważeniem o jej ośmiu latach i przeciw odwaga stawiać im swój poważny wiek i doświadczenie. Utrzymywał, że chłopiec, który kończy lat czternaście, jeśli nie jest jeszcze zupełnie dorosłym, to przynajmniej nie jest już dzieckiem, a natomiast zdolny już jest do wszelkiego rodzaju czynów bohaterskich, zwłaszcza jeśli ma w sobie krew polską i fancuską.`,
    `Tymczasem w domu czekała ich podczas obiadu dobra nowina. Panowie Tarkowski i Raw-lison byli zaproszeni przed kilku tygodniami, jako biegli inżynierowie, do obejrzenia i oceny robót prowadzonych przy całej sieci kanałów w prowincji El-Fajum, w okolicach miasta Medinet blisko jeziora Karoun oraz wzdłuż rzeki Jussef i Nilu. Mieli tam zabawić koło miesiąca i uzyskali na to urlopy od własnej kompanii.`,
    `Ale wakacje jego zaczynały się dopiero za kilka dni, ponieważ zaś rewizja robót przy kanałach była sprawą pilną i starsi panowie nie mogli tracić czasu, ułożyli się przeto, że wyjadą niezwłocznie, a dzieci wraz z panią Olivier w tydzień później. I Nel, i Staś mieli ochotę jechać zaraz, ale Staś nie śmiał o to prosić. Poczęli natomiast wypytywać o rozmaite sprawy tyczące podróży i z nowymi wybuchami radości przyjęli wiadomość, że nie będą mieszkali w niewygodnych utrzymywanych przez Greków hotelach, ale w namiotach dostarczonych przez Towarzystwo Podróżnicze Cooka.`,




];
export default text;
